// @generated by scripts/gen-error-codes.mjs from contracts/error-codes.json — DO NOT EDIT.
#![allow(dead_code)]

//! The closed error-code registry (server mirror), generated from contracts/error-codes.json.

/// One row of code metadata.
pub struct CodeMeta {
    pub code: &'static str,
    pub domain: &'static str,
    pub title: &'static str,
    pub retriable: bool,
    pub action: Option<&'static str>,
}

pub const BELOW_GC_FLOOR: &str = "below_gc_floor";
pub const QUOTA_EXCEEDED: &str = "quota_exceeded";
pub const RATE_LIMITED: &str = "rate_limited";
pub const VERSION_CONFLICT: &str = "version_conflict";
pub const COVERED_ANOMALY: &str = "covered_anomaly";
pub const HEAD_ROLLBACK: &str = "head_rollback";
pub const INVALID_REQUEST: &str = "invalid_request";
pub const ACCESS_DENIED: &str = "access_denied";
pub const NOT_FOUND: &str = "not_found";
pub const UNAVAILABLE: &str = "unavailable";
pub const REQUEST_FAILED: &str = "request_failed";
pub const OFFLINE: &str = "offline";
pub const TIMEOUT: &str = "timeout";
pub const AUTH_REQUIRED: &str = "auth_required";
pub const SESSION_EXPIRED: &str = "session_expired";
pub const SIGN_IN_FAILED: &str = "sign_in_failed";
pub const SIGN_UP_FAILED: &str = "sign_up_failed";
pub const EMAIL_TAKEN: &str = "email_taken";
pub const RECIPIENT_PIN_MISMATCH: &str = "recipient_pin_mismatch";
pub const UNREGISTERED: &str = "unregistered";
pub const STALE_TIMESTAMP: &str = "stale_timestamp";
pub const BAD_SIGNATURE: &str = "bad_signature";
pub const MEMBER_ID_MISMATCH: &str = "member_id_mismatch";
pub const IDENTITY_CONFLICT: &str = "identity_conflict";
pub const WRONG_PASSPHRASE: &str = "wrong_passphrase";
pub const TAMPERED_ANCHOR: &str = "tampered_anchor";
pub const REVISION_ROLLBACK: &str = "revision_rollback";
pub const GENERATION_ROLLBACK: &str = "generation_rollback";
pub const RECOVERY_CODE_INVALID: &str = "recovery_code_invalid";
pub const KEYRING_VERIFY_FAILED: &str = "keyring_verify_failed";
pub const DECRYPT_FAILED: &str = "decrypt_failed";
pub const STORAGE_QUOTA: &str = "storage_quota";
pub const STORAGE_BLOCKED: &str = "storage_blocked";
pub const STORAGE_CORRUPT: &str = "storage_corrupt";
pub const WORKER_UNAVAILABLE: &str = "worker_unavailable";
pub const INTERNAL: &str = "internal";

/// Every code + its metadata, in source order.
pub const ERROR_CODES: &[CodeMeta] = &[
    CodeMeta { code: "below_gc_floor", domain: "sync", title: "Below the GC floor", retriable: false, action: Some("bootstrap") },
    CodeMeta { code: "quota_exceeded", domain: "sync", title: "Storage quota exceeded", retriable: false, action: Some("upgrade") },
    CodeMeta { code: "rate_limited", domain: "sync", title: "Rate limited", retriable: true, action: Some("retry") },
    CodeMeta { code: "version_conflict", domain: "sync", title: "Version conflict", retriable: true, action: Some("retry") },
    CodeMeta { code: "covered_anomaly", domain: "sync", title: "Coverage inconsistency", retriable: false, action: Some("contact") },
    CodeMeta { code: "head_rollback", domain: "sync", title: "Head pointer moved backward", retriable: false, action: None },
    CodeMeta { code: "invalid_request", domain: "sync", title: "Invalid request", retriable: false, action: Some("contact") },
    CodeMeta { code: "access_denied", domain: "sync", title: "Access denied", retriable: false, action: None },
    CodeMeta { code: "not_found", domain: "sync", title: "Not found", retriable: false, action: None },
    CodeMeta { code: "unavailable", domain: "sync", title: "Service unavailable", retriable: true, action: Some("retry") },
    CodeMeta { code: "request_failed", domain: "sync", title: "Request failed", retriable: true, action: Some("retry") },
    CodeMeta { code: "offline", domain: "sync", title: "Offline", retriable: true, action: Some("retry") },
    CodeMeta { code: "timeout", domain: "sync", title: "Request timed out", retriable: true, action: Some("retry") },
    CodeMeta { code: "auth_required", domain: "auth", title: "Authentication required", retriable: false, action: Some("reauth") },
    CodeMeta { code: "session_expired", domain: "auth", title: "Session expired", retriable: false, action: Some("reauth") },
    CodeMeta { code: "sign_in_failed", domain: "auth", title: "Sign-in failed", retriable: false, action: None },
    CodeMeta { code: "sign_up_failed", domain: "auth", title: "Sign-up failed", retriable: false, action: None },
    CodeMeta { code: "email_taken", domain: "auth", title: "Email already registered", retriable: false, action: None },
    CodeMeta { code: "recipient_pin_mismatch", domain: "auth", title: "This invite is for a different email", retriable: false, action: Some("reauth") },
    CodeMeta { code: "unregistered", domain: "auth", title: "Account not registered", retriable: false, action: Some("reauth") },
    CodeMeta { code: "stale_timestamp", domain: "auth", title: "Registration timestamp out of window", retriable: false, action: None },
    CodeMeta { code: "bad_signature", domain: "auth", title: "Registration proof invalid", retriable: false, action: Some("contact") },
    CodeMeta { code: "member_id_mismatch", domain: "auth", title: "Member id not self-certifying", retriable: false, action: Some("contact") },
    CodeMeta { code: "identity_conflict", domain: "auth", title: "Identity already bound", retriable: false, action: None },
    CodeMeta { code: "wrong_passphrase", domain: "vault", title: "Wrong passphrase", retriable: false, action: None },
    CodeMeta { code: "tampered_anchor", domain: "vault", title: "Tree verification failed", retriable: false, action: Some("contact") },
    CodeMeta { code: "revision_rollback", domain: "vault", title: "Version rollback detected", retriable: false, action: None },
    CodeMeta { code: "generation_rollback", domain: "vault", title: "Account backup rolled back", retriable: false, action: None },
    CodeMeta { code: "recovery_code_invalid", domain: "vault", title: "Invalid recovery code", retriable: false, action: None },
    CodeMeta { code: "keyring_verify_failed", domain: "vault", title: "Keyring verification failed", retriable: false, action: Some("contact") },
    CodeMeta { code: "decrypt_failed", domain: "vault", title: "Decryption failed", retriable: false, action: Some("contact") },
    CodeMeta { code: "storage_quota", domain: "storage", title: "Local storage full", retriable: false, action: Some("contact") },
    CodeMeta { code: "storage_blocked", domain: "storage", title: "Local storage unavailable", retriable: false, action: Some("contact") },
    CodeMeta { code: "storage_corrupt", domain: "storage", title: "Local storage corrupt", retriable: false, action: Some("contact") },
    CodeMeta { code: "worker_unavailable", domain: "app", title: "Background worker unavailable", retriable: false, action: Some("upgrade") },
    CodeMeta { code: "internal", domain: "app", title: "Internal error", retriable: false, action: Some("contact") },
];

/// The stable RFC 9457 `title` for a code (falls back to a generic label for an unknown code).
#[must_use]
pub fn title_for(code: &str) -> &'static str {
    ERROR_CODES.iter().find(|m| m.code == code).map_or("Error", |m| m.title)
}

/// Interpolation args for `quota_exceeded`.
pub struct QuotaExceededArgs {
    pub limit: u64,
    pub used: u64,
}

